---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: insert-license
        files: (Gemfile|.*\.(tf(vars)?|y?ml))$
        args:
        - --license-filepath
        - .license_header.txt
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.16.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
