---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: insert-license
        files: (Gemfile|Makefile|.*\.(tf(vars)?|y?ml))$
        args:
        - --license-filepath
        - .license_header.txt
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.44.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: git://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate
